### PR TITLE
Solution for #92.

### PR DESCRIPTION
**Pull request by 00anwi**
Fix for #92 

image

### CODE REVIEW

**Comment by prosthetichead** [comment]
I'm little confused, is this going to mark everything as success / complete even though the game wasn't found?

**Comment by 00anwi** [comment]
I changed the status message from "Complete" to "Only Local Media Complete" now.

**Comment by 00anwi** [comment]
@prosthetichead I have another big pull request that's not complete yet at [SystemMedia](https://github.com/00anwi/GarlicPress/tree/SystemMedia) that will be done soon that will also have this done.

But I'll make a draft request so you can come with some feedback.

**Comment by prosthetichead** [comment]
Could it be a option tick box on the options tab? Then it can still mark the job as complete.

**Comment by 00anwi** [comment]
Is this what you were thinking?
The change is committed to this pull request.

image

**Review by prosthetichead — APPROVED** [review]
👍Looks good, Will merge it in and do a release soon with a few more fixes

**Pull request merged**
