### PR TITLE
Media Layer Editor

### PR DESCRIPTION
**Pull request by 00anwi**
### Summary
This pull request introduces a variety of changes including a new Media Layer Editor, updates to the media download system, the addition of various filters, and more.

---

### Changes
- **Framework & Dependencies**:
  - Updated to `.NET 7` for enhanced Blazor functionality and Blazor WebView.
  - Added client-side libraries restore - currently, only fabric.js for the Media Layer Editor.
  
- **Media Handling**:
  - Introduced a Media Layer Editor.
  - Game media now gets added with game id and remains undeleted until program termination. Option to not delete the temp folder on exit has been added (UI integration pending).
  - Enhanced the download media function to utilize multiple threads based on user's screenscraper.fr subscription.
  - Media selection now considers region order. EU added to the region setting link.
  - Media layers have a new rotation feature.
  - Updated PreviewForm to use the selected MediaLayoutCollection from SettingsForm. 
 
https://github.com/prosthetichead/GarlicPress/assets/8648447/97aaf2d6-3cca-4e14-b77d-5a269c4def50

  - Implemented filter components in Blazor: SaturationFilter, ContrastFilter, BrightnessFilter, BlurFilter, GaussianBlurFilter, GradientFilter (Color & Transparency variations), TransparencyFilter, and GrayscaleFilter. (Images provided below).
  - Filters can be stacked for cumulative effects.
  - MediaLayoutCollection now supports reading and writing filter options.
  

- **File & Folder Management**:
  - Added path constants. Moved some assets to `wwwroot/assets` for Blazor accessibility.
  - Updated `.gitignore` to exclude specific files such as background.png, mediaLayout.json, and more.
  - Implemented `.editorconfig` to suppress file-scoped namespace warnings.
  - Added media layout collection functionality: supports multiple saved lists of media layers.

- **Garbage Collection**:
  - Modified garbage collection settings in `.csproj` may not be needed as I changed back from Microsoft.NET.Sdk.Web to Microsoft.NET.Sdk.Razor.

- **UI & Styles**:
  - Added Tailwind CSS configuration files. Manual rebuilding is possible through the VS extension or node.js. 
  
---

### Media Layer Editor

image

#### Media Layer Collections

- **Selecting Collections:** You can select a Media Layer Collection from a dropdown list.

- **Add Media Layer Collection:** Clicking the 'Add Media Layer Collection' button opens a modal where you can input the desired name and select an existing MediaLayerCollection as a template, or leave unselected for a clean collection. Upon submission, it creates a new Media Layer Collection.

- **Edit Media Layer Collection:** Allows you to rename an existing Media Layer Collection by opening a modal and inputting the new name.

- **Delete Media Layer Collection:** By clicking the 'Delete Media Layer Collection' button, a confirmation modal appears to confirm the deletion. Once confirmed, it will delete the selected collection.

#### Preview Features

* While editing, a preview is generated to closely resemble its appearance on RG35XX.
* The preview leverages game lists, font, position, text alignment, color, and other theme details. Note that I have not tested getting these things from RG35XX..

#### Game Media

- **Loading Game Media:** The editor can fetch all available game media from ScreenScraper that matches with `GetAllMediaTypes`. Media will be loaded depending on the region order set, gets only first game media thats gets found from region order.

- **Ordering Game Media:** The draw order of game media can be altered using the Page Up/Page Down keys. To delete an item, simply press the delete key on the keyboard.

#### Editing Window

- **Drive, System, and Game Dropdowns:** The editing window provides dropdown options to select 'Drive', 'System', and 'Game'.

- **Canvas:** The canvas displays the media layers in their respective order and dimensions. The canvas allows for direct manipulation of media items.

- **Media Layer Controls:** It provides options to apply filters and make other adjustments to the selected media layer.

- **Game Art:** You can retrieve game art by pressing the 'Get Game Art' button. It fetches and displays all the available game arts. By pressing a art it's gets added to the preview window and it's possible to edit position, angle, size, order etc.

---
### Local files

- **Added so it's possible to have local files with media generation**
image

---

### Closed Issues
- **[#52](https://github.com/prosthetichead/GarlicPress/issues/52)**: This PR should also address and close [#58](https://github.com/prosthetichead/GarlicPress/issues/58), though note that there is no support for Skraper XML files. 

https://github.com/prosthetichead/GarlicPress/assets/8648447/7ccdcdd7-d371-404b-91ec-0273635daa24

- **[#46](https://github.com/prosthetichead/GarlicPress/issues/46)**: Addressed by introducing a feature to set region order in settings. 

image

---

### Questions:
- Are you okay with the frameworks, tailwind, blazor, fabric.js etc?

### Notes:
- This PR has not been tested on a RG35XX. Please conduct tests before merging. If any changes need breaking down into separate PRs or if there are any other modifications required, please comment. I will hopefully recieve my RG35XX next week.

### Filters:
**SaturationFilter**

image
---

**ContrastFilter**

image
---
**BrightnessFilter**

image
---
**BlurFilter**

image
---
**GaussianBlurFilter**

image
---
**GradientFilter**
  - **Color Gradient**

  image

  - **Transparency gradient set opacity to 0%**
  image
---
**TransparencyFilter**

image
---
**GrayscaleFilter**

image

**It's possible to stack filters for desired effect.**
image

### CODE REVIEW

**Comment by prosthetichead** [comment]
cool thanks man, I will check out the branch soon and give it a try! 

I have never used blazer or Tailwind so I will give them a go when I have some free time hopefully this weekend or next. Got a large project going live at work this weekend so may not get a chance to look at it closely sorry.

**Comment by ashcolman** [comment]
I'm happy for you to add #58 and #52 to this branch or if you wanted to jump on a few quick wins in the open issues.

I'm not going to be able to look at this branch closely until next weekend at the earliest so plenty of time to work on it more to include more.

I had left open a space on the art download screen also for selection of media layouts at time of downloading art also.

**Comment by 00anwi** [comment]
I have updated the design to be less jarring from going from WinForms UI to Blazor UI.
image

Added button to access the editor from MainForm.
image

Added Selection of Media Layer Collection in GameArtUpdateForm.
image

Resized everything in MediaLayerEditor and made it more responsive to size changes. 

It is now tested against a RG35XX and everything I've tried works, had to fix some bugs when I got my RG35XX.

Please let me know what you think @prosthetichead.

I have some more things I want to implement like System media etc.

**Comment by prosthetichead** [comment]
This is Looking amazing @00anwi!!
I have been very busy this last couple of weeks and even without a computer for some of it! But back online now and I want to get this merged into master soon!!

**Review by prosthetichead — APPROVED** [review]
👌

**Comment by 00anwi** [comment]
> 👌

😁

**Pull request merged**
